// src/constants/tarotImages.ts

export const TAROT_IMAGES: Record<string, any> = {
    // Card back
    card_back: require('../../assets/cards/card_back.jpg'),

    // Major arcana
    major_0: require('../../assets/cards/major_0.jpg'),
    major_1: require('../../assets/cards/major_1.jpg'),
    major_2: require('../../assets/cards/major_2.jpg'),
    major_3: require('../../assets/cards/major_3.jpg'),
    major_4: require('../../assets/cards/major_4.jpg'),
    major_5: require('../../assets/cards/major_5.jpg'),
    major_6: require('../../assets/cards/major_6.jpg'),
    major_7: require('../../assets/cards/major_7.jpg'),
    major_8: require('../../assets/cards/major_8.jpg'),
    major_9: require('../../assets/cards/major_9.jpg'),
    major_10: require('../../assets/cards/major_10.jpg'),
    major_11: require('../../assets/cards/major_11.jpg'),
    major_12: require('../../assets/cards/major_12.jpg'),
    major_13: require('../../assets/cards/major_13.jpg'),
    major_14: require('../../assets/cards/major_14.jpg'),
    major_15: require('../../assets/cards/major_15.jpg'),
    major_16: require('../../assets/cards/major_16.jpg'),
    major_17: require('../../assets/cards/major_17.jpg'),
    major_18: require('../../assets/cards/major_18.jpg'),
    major_19: require('../../assets/cards/major_19.jpg'),
    major_20: require('../../assets/cards/major_20.jpg'),
    major_21: require('../../assets/cards/major_21.jpg'),

    // Wands
    minor_wands_1: require('../../assets/cards/minor_wands_1.jpg'),
    minor_wands_2: require('../../assets/cards/minor_wands_2.jpg'),
    minor_wands_3: require('../../assets/cards/minor_wands_3.jpg'),
    minor_wands_4: require('../../assets/cards/minor_wands_4.jpg'),
    minor_wands_5: require('../../assets/cards/minor_wands_5.jpg'),
    minor_wands_6: require('../../assets/cards/minor_wands_6.jpg'),
    minor_wands_7: require('../../assets/cards/minor_wands_7.jpg'),
    minor_wands_8: require('../../assets/cards/minor_wands_8.jpg'),
    minor_wands_9: require('../../assets/cards/minor_wands_9.jpg'),
    minor_wands_10: require('../../assets/cards/minor_wands_10.jpg'),
    minor_wands_11: require('../../assets/cards/minor_wands_11.jpg'),
    minor_wands_12: require('../../assets/cards/minor_wands_12.jpg'),
    minor_wands_13: require('../../assets/cards/minor_wands_13.jpg'),
    minor_wands_14: require('../../assets/cards/minor_wands_14.jpg'),

    // Cups
    minor_cups_1: require('../../assets/cards/minor_cups_1.jpg'),
    minor_cups_2: require('../../assets/cards/minor_cups_2.jpg'),
    minor_cups_3: require('../../assets/cards/minor_cups_3.jpg'),
    minor_cups_4: require('../../assets/cards/minor_cups_4.jpg'),
    minor_cups_5: require('../../assets/cards/minor_cups_5.jpg'),
    minor_cups_6: require('../../assets/cards/minor_cups_6.jpg'),
    minor_cups_7: require('../../assets/cards/minor_cups_7.jpg'),
    minor_cups_8: require('../../assets/cards/minor_cups_8.jpg'),
    minor_cups_9: require('../../assets/cards/minor_cups_9.jpg'),
    minor_cups_10: require('../../assets/cards/minor_cups_10.jpg'),
    minor_cups_11: require('../../assets/cards/minor_cups_11.jpg'),
    minor_cups_12: require('../../assets/cards/minor_cups_12.jpg'),
    minor_cups_13: require('../../assets/cards/minor_cups_13.jpg'),
    minor_cups_14: require('../../assets/cards/minor_cups_14.jpg'),

    // Swords
    minor_swords_1: require('../../assets/cards/minor_swords_1.jpg'),
    minor_swords_2: require('../../assets/cards/minor_swords_2.jpg'),
    minor_swords_3: require('../../assets/cards/minor_swords_3.jpg'),
    minor_swords_4: require('../../assets/cards/minor_swords_4.jpg'),
    minor_swords_5: require('../../assets/cards/minor_swords_5.jpg'),
    minor_swords_6: require('../../assets/cards/minor_swords_6.jpg'),
    minor_swords_7: require('../../assets/cards/minor_swords_7.jpg'),
    minor_swords_8: require('../../assets/cards/minor_swords_8.jpg'),
    minor_swords_9: require('../../assets/cards/minor_swords_9.jpg'),
    minor_swords_10: require('../../assets/cards/minor_swords_10.jpg'),
    minor_swords_11: require('../../assets/cards/minor_swords_11.jpg'),
    minor_swords_12: require('../../assets/cards/minor_swords_12.jpg'),
    minor_swords_13: require('../../assets/cards/minor_swords_13.jpg'),
    minor_swords_14: require('../../assets/cards/minor_swords_14.jpg'),

    // Pentacles
    minor_pentacles_1: require('../../assets/cards/minor_pentacles_1.jpg'),
    minor_pentacles_2: require('../../assets/cards/minor_pentacles_2.jpg'),
    minor_pentacles_3: require('../../assets/cards/minor_pentacles_3.jpg'),
    minor_pentacles_4: require('../../assets/cards/minor_pentacles_4.jpg'),
    minor_pentacles_5: require('../../assets/cards/minor_pentacles_5.jpg'),
    minor_pentacles_6: require('../../assets/cards/minor_pentacles_6.jpg'),
    minor_pentacles_7: require('../../assets/cards/minor_pentacles_7.jpg'),
    minor_pentacles_8: require('../../assets/cards/minor_pentacles_8.jpg'),
    minor_pentacles_9: require('../../assets/cards/minor_pentacles_9.jpg'),
    minor_pentacles_10: require('../../assets/cards/minor_pentacles_10.jpg'),
    minor_pentacles_11: require('../../assets/cards/minor_pentacles_11.jpg'),
    minor_pentacles_12: require('../../assets/cards/minor_pentacles_12.jpg'),
    minor_pentacles_13: require('../../assets/cards/minor_pentacles_13.jpg'),
    minor_pentacles_14: require('../../assets/cards/minor_pentacles_14.jpg'),
}
